name: fluttour
description: A medium Flutter base-source
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.0.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.3
  graphql: ^5.1.3
  # State management
  flutter_bloc: ^8.1.2
  # User interface
  flutter_svg: ^2.0.2
  flutter_screenutil: ^5.6.1
  # Annotation
  meta: any
  json_annotation: ^4.8.0
  # Data type
  equatable: ^2.0.5
  # Language
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3
  mockito: ^5.3.2
  analyzer: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/locales/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400